# -*- coding: utf-8 -*-
"""06_분석예제_7팀_정지원.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MI-Fh0ruCY3ZgmD0WZ8ZNj6vMCvn2je2

# **[Mission] 기초 통계와 데이터 시각화**  
**┗ 건강검진 데이터 시각화하기**
---
> **목차(Context)**

* 데이터 살펴보기
* EDA
"""

### 개발환경 세팅하기

# ▶ 한글 폰트 다운로드
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# ▶ 한글 폰트 설정하기
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] =False

# ▶ Warnings 제거
import warnings
warnings.filterwarnings('ignore')

# ▶ Google drive mount or 폴더 클릭 후 구글드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

"""## **데이터 준비하기**
---

> **데이터 준비하기**

- 데이터 출처 : [공공데이터 포털](https://www.data.go.kr/data/15007122/fileData.do#/layer_data_infomation) `국민건강보험공단_건강검진정보`

- 데이터 명세  

| No. | 표준항목명          | 영문명            | 설명                                                                                                           | 표현형식/단위          | 예시         |
|-----|-----------------|------------------|---------------------------------------------------------------------------------------------------------------|---------------------|--------------|
| 1   | 기준년도          | HCHK_YEAR        | 해당 정보의 기준년도를 제공함                                                                                  | YYYY                | 2009         |
| 2   | 가입자일련번호       | IDV_ID           | 해당가입자에 부여한 일련번호                                                                                  | 1 ~ 1,000,000       | 1            |
| 3   | 시도코드          | SIDO             | 해당 수진자 거주지의 시도코드                                                                                  | -                   | 26           |
| 4   | 성별              | SEX              | 해당 정보 대상자의 성별을 제공함                                                                               | 성별 : 1(남자), 2(여자) | 1            |
| 5   | 연령대코드(5세단위)    | AGE_GROUP        | 기준년도에 수진자의 나이를 5세 단위로 그룹화하여 구분한 코드                                                     | 5세 단위 그룹화, 85세 이상은 85+로 그룹화 | -            |
| 6   | 신장(5cm단위)     | HEIGHT           | 검진자의 키(5CM 단위)                                                                                          | N/Cm                | 140          |
| 7   | 체중(5kg단위)     | WEIGHT           | 검진자의 몸무게(5KG 단위)                                                                                      | N/Kg                | 45           |
| 8   | 허리둘레          | WAIST            | 검진자의 허리둘레                                                                                              | N/Cm                | 82           |
| 9   | 시력(좌)          | SIGHT_LEFT       | 수검자의 좌측 눈의 시력                                                                                        | N                   | 0.5          |
| 10  | 시력(우)          | SIGHT_RIGHT      | 수검자의 우측 눈의 시력                                                                                        | N                   | 0.5          |
| 11  | 청력(좌)          | HEAR_LEFT        | 수검자의 좌측 귀의 청력                                                                                        | N                   | 1            |
| 12  | 청력(우)          | HEAR_RIGHT       | 수검자의 우측 귀의 청력                                                                                        | N                   | 1            |
| 13  | 수축기혈압         | BP_HIGH          | 검진자의 최고 혈압으로 심장이 수축해서 강한 힘으로 혈액을 동맥에 보낼 때의 혈관 내압                                   | N/mmHg              | 140          |
| 14  | 이완기혈압         | BP_LWST          | 검진자의 최저 혈압으로 심장의 완기시의 혈압                                                                      | N/mmHg              | 81           |
| 15  | 식전혈당(공복혈당)    | BLDS             | 검진자 식사 전 혈당(혈액 100ml당 함유 되어 있는 포도당의 농도) 수치                                               | N/mg/dL             | 94           |
| 16  | 총콜레스테롤        | TOT_CHOLE        | 혈청 중의 에스텔형, 비에스테형(유리)콜레스테롤의 합                                                               | N/mg/dL             | 164          |
| 17  | 트리글리세라이드    | TRIGLYCERIDE     | 단순지질 혹은 중성지질을 뜻함                                                                                    | N/mg/dL             | 94           |
| 18  | HDL콜레스테롤      | HDL_CHOLE        | HDL(고밀도 리포단백질)에 포함되는 콜레스테롤                                                                      | N/mg/dL             | 45           |
| 19  | LDL콜레스테롤      | LDL_CHOLE        | LDL(저밀도 리포단백질)에 함유된 콜레스테롤                                                                        | N/mg/dL             | 150, 130     |
| 20  | 혈색소            | HMG              | 혈액이나 혈구 속에 존재하는 색소단백으로 글로빈(globin)과 엠(heme)으로 구성되며 혈중의 산소운반체로서의 역할 수행       | N/g/dL              | 15.3984375   |
| 21  | 요단백            | OLIG_PROTE_CD    | 소변에 단백질이 섞여 나오는 것                                                                                  | N                   | 1            |
| 22  | 혈청크레아티닌       | CREATININE       | 크레아틴의 탈수물로 내인성 단백대사의 종말산물로서 신장에서 배설되고 그 증감은 음식물에 관계없이 근육의 발육과 운동에 관계함 | N/mg/dL             | 0.8          |
| 23  | 혈청지오티(AST)    | AST              | 간 기능을 나타내는 혈액검사상의 수치, 간세포 이외에 심장, 신장, 뇌, 근육 등에도 존재하는 효소로 이러한 세포들이 손상을 받는 경우 농도가 증가함 | N/IU/L              | 12           |
| 24  | 혈청지피티(ALT)    | ALT              | 간 기능을 나타내는 혈액검사상의 수치, ALT는 주로 간세포 안에 존재하는 효소로, 간세포가 손상을 받는 경우 농도가 증가함        | N/U/L               | 15           |
| 25  | 감마지티피         | GAMMA_GTP        | 간 기능을 나타내는 혈액검사상의 수치, 간 내의 쓸개관(담관)에 존재하는 효소로 글루타민산을 외부에 펩티드나 아미노산 등으로 옮기는 작용을 함 | N/U/L               | 119, 114     |
| 26  | 흡연상태           | SMK_STAT_TYPE_CD | 해당 수검자의 흡연 상태 여부                                                                                    | N                   | 1            |
| 27  | 음주여부           | DRK_YN           | 해당 수검자의 음주 상태 여부                                                                                    | N/Y                 | 1            |
| 28  | 구강검진수검여부     | HCHK_OE_INSPEC_YN | 해당 검진자가 구강검진을 선택하여 검진하였는지 여부에 대한 항목                                                   | N/Y                 | 1            |
| 29  | 치아우식증유무       | CRS_YN           | 해당 수검자의 치아우식증 유무                                                                                   | N                   | 1            |
| 30  | 치석              | TTR_YN           | 해당 수검자의 치석 여부                                                                                         | N/Y                 | 1            |

     

"""

# 필요한 라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Pandas 보기 옵션
pd.set_option('display.max_columns',100)

"""### 문제1. 데이터 불러오기
: 제공된 `./국민건강보험공단_건강검진정보_20221231.CSV` 파일을 불러오세요. 한글 폰트가 깨질 경우, 인코딩을 확인해보세요.
"""

data_path = '국민건강보험공단_건강검진정보_20221231.CSV'
health_df = pd.read_csv(data_path, encoding='euc-kr')

"""## **EDA : Data 살펴보기**  
---

* 수집된 데이터의 기본 정보들을 확인  

  (1) Data shape(형태) 확인

  (2) Data type 확인

  (3) Null값 확인 (※ 빈 값의 Data)

  (4) Outlier 확인 (※ 정상적인 범주를 벗어난 Data)

### 전체적인 데이터 살펴보기

#### 문제2. 데이터의 형태를 확인해보세요.
- 몇 개의 데이터가 존재하나요?
- 몇 개의 특성이 존재하나요?
"""

# Data 형태 확인
health_df.shape

"""#### 문제3. 데이터의 타입을 확인해보세요.
- 어떤 특성들이 데이터에 포함되어 있나요?
- 각 특성의 값은 어떤 데이터 타입으로 구성되어 있나요?
"""

# Data type 확인
health_df.info()

# 데이터 값 확인 - 상위 30행을 출력하여 데이터를 확인해보세요.
health_df.head(30)

"""#### 문제4 : 결측치 확인하기
- 각 특성 별로 결측치 개수와 비율을 확인해보세요.
- 결측치의 양상이 특성마다 차이가 난다면, 왜 그런 차이가 발생했을까요?
"""

# 아래 예시는 결측치가 없는 열은 필터링해서 확인하였습니다
health_df.isnull().sum()

"""#### 문제5 : 결측치 시각화하기
- 데이터프레임에서 결측치가 존재하는 부분을 시각화해보세요.
"""

!pip install missingno

import missingno as msno

msno.matrix(health_df)
plt.show()

"""### 어떤 데이터에서 결측치가 관측되었나요? 해당 데이터는 어떻게 전처리하는 게 좋을까요?
- 데이터의 양이 많아 결측치가 있는 행이 포함되어있으면 삭제를 진행
"""

health_df = health_df.dropna()
health_df.shape

"""#### 문제6 : 중복값 확인하기
- 데이터에 중복값이 있는 지 확인해보세요. 만약 있다면, 제거하세요.
"""

health_df.tail(2)

health_df.duplicated().sum()

health_id_condition = health_df.duplicated(subset = '가입자일련번호', keep=False)
health_df[health_id_condition]

"""```
#중복데이터 제거코드
health_df.drop_duplicates(subset=['가입일련번호'], inplace=True)
```

#### 문제7 : 연령대 코드 수정하기
- 현재 데이터는 연령대를 코드로 제공하고 있습니다. 연령대 코드가 의미하는 바는 다음 표와 같습니다.
- `연령대`라는 새로운 열을 만들고, 연령대 코드를 의미하는 연령대로 매핑해보세요.
"""

health_df['연령대코드(5세단위)'].unique()

# 연령대 코드 매핑
age_group_mapping = {
    1: "0-4", 2: "5-9", 3: "10-14", 4: "15-19", 5: "20-24",
    6: "25-29", 7: "30-34", 8: "35-39", 9: "40-44", 10: "45-49",
    11: "50-54", 12: "55-59", 13: "60-64", 14: "65-69", 15: "70-74",
    16: "75-79", 17: "80-84", 18: "85+"
}

# 연령대 코드를 새로운 매핑으로 업데이트 해보세요
health_df.rename(columns={'연령대코드(5세단위)':'연령대(5세단위)'}, inplace=True)
health_df.columns

health_df['연령대(5세단위)'] = health_df['연령대(5세단위)'].replace(age_group_mapping)
health_df['연령대(5세단위)'].unique()

health_df.head(1)

"""### 개별 데이터 살펴보기

#### 문제8 : 수치형 데이터와 범주형 데이터 구분하기
- 수치형 데이터와 범주형 데이터는 데이터를 살펴보는데 차이가 있습니다. 수치형 데이터와 범주형 데이터를 구분하세요.
"""

health_df.head(5)

# 범주형 데이터
print('범주형데이터_values')
print(health_df['연령대(5세단위)'].unique())
print(health_df['음주여부'].unique())
print(health_df['성별'].unique())
print(health_df['요단백'].unique())
print(health_df['흡연상태'].unique())
print(health_df['구강검진수검여부'].unique())
print(health_df['치아우식증유무'].unique())
print(health_df['치석'].unique())

# 수치형 데이터
# 수치형 데이터
num_col = ['신장(5cm단위)', '체중(5kg단위)', '허리둘레', '시력(좌)', '시력(우)', '청력(좌)', '청력(우)', '수축기혈압', '이완기혈압', '식전혈당(공복혈당)', '총콜레스테롤', '트리글리세라이드', 'HDL콜레스테롤', 'LDL콜레스테롤', '혈색소', '혈청크레아티닌', '혈청지오티(AST)', '혈청지피티(ALT)', '감마지티피'   ]
# 범주형 데이터
cate_col = ['성별', '연령대(5세단위)', '요단백', '흡연상태', '음주여부', '구강검진수검여부', '치아우식증유무', '치석']

#수치형
health_df[num_col].columns

#범주형
health_df[cate_col].columns

"""#### 문제9 : 기술통계량 확인하기
- 수치형 데이터와 범주형 데이터의 기술통계량을 확인해보세요.
"""

# 수치형 변수의 기술 통계량
health_df.head(2)

health_df.info()

health_df[num_col].describe()

health_df[cate_col].describe()

# 각 변수들은 어떤 특징을 가지고 있나요?
- 평균, 표준편차, 중앙값, 최솟값, 최댓값 확인가능
- 이상치 확인

# 범주형 변수의 기술 통계량
cate_col = ['성별', '연령대(5세단위)', '요단백', '흡연상태', '음주여부', '구강검진수검여부', '치아우식증유무', '치석']
health_df[cate_col] = health_df[cate_col].astype('category')
cate_columns = health_df.select_dtypes(include = ['category'])

cate_columns.describe()

health_df[cate_col].value_counts()

"""# 각 변수들은 어떤 특징을 가지고 있나요?
- 연령대의 경우 40-44세의 비율이 가장 높게나옴

#### 문제10 : 분포 확인하기
- 각 데이터가 어떻게 분포되어 있는지 확인해보세요.
- 데이터를 구성하는 각 속성값이 예측한 범위와 분포를 갖는지, 아니라면 그 이유가 무엇인지 확인해보세요.
"""

health_df[num_col].head()

health_num = health_df[num_col]

health_num.hist(figsize=(15, 15), bins = 20)
plt.suptitle('수치형 데이터')
plt.show()

"""### 속성 간의 관계 살펴보기

#### 문제11 : 상관관계 분석하기
- 수치형 데이터 간의 상관 관계를 계산하고 히트맵을 사용해 시각화해보세요.
"""

plt.figure(figsize=(15, 15))

sns.heatmap(health_df[num_col].corr(), annot=True, fmt='.2f', cmap='YlGnBu')
plt.title("수치형 데이터 상관관계")

plt.show()

# 위 시각화에서 찾을 수 있는 관계성은 어떤 것이 있나요?

# HDL 콜레스테롤은 체중, 허리둘레, 트리글리세라이드와 음의 상관관계를 가지고있음.
# LDL 콜레스테롤은 총클레스테롤과 큰 양의 상관관계를 가지고있음.

"""#### 문제12 : 수치형 변수들 간의 산점도 및 각 변수의 히스토그램을 그려 보세요

- 4가지 변수('신장(5cm단위)', '체중(5kg단위)', '허리둘레', '수축기혈압')에 대한 시각화를 진행해보세요.
"""

# 수치형 변수들에 대한 Pair Plot 그리기
select_columns = ['신장(5cm단위)','체중(5kg단위)', '허리둘레', '수축기혈압']
sns.pairplot(health_df[select_columns], diag_kind='hist')
plt.suptitle('4가지 변수 산점도', y = 1.02)
plt.show()

"""#### 문제13 : 성별에 따른 몇 가지 주요 수치형 변수(신장, 체중, 허리둘레, 수축기혈압)의 기술 통계 비교하기

- 범주형 변수에 따른 수치형 변수의 분포 분석해봅시다. 성별이 주요 건강 지표(신장, 체중, 허리둘레, 수축기혈압)에 어떻게 영향을 미치는지 파악하고 싶습니다.

- 카테고리별 수치형 변수의 기술 통계 분석: 각 카테고리별로 수치형 변수의 평균, 중앙값, 분산 등을 비교합니다.
"""

health_df.head(2)

health_df.groupby(by='성별')[select_columns].agg(['mean', 'median', 'std', 'var'])

"""#### 문제14 : 성별에 따른 몇 가지 주요 수치형 변수(신장, 체중, 허리둘레, 수축기혈압)의 분포를 비교하기

- 성별에 따른 몇 가지 주요 수치형 변수(신장, 체중, 허리둘레, 수축기혈압)의 분포를 시각화하여 비교해보세요.
- 시각화 방법은 자유롭게 선택하셔도 됩니다.
"""

select_columns = ['신장(5cm단위)','체중(5kg단위)', '허리둘레', '수축기혈압']

for col in select_columns:
    plt.figure(figsize = (10, 5))

    sns.boxplot(x='성별', y=col, data=health_df)
    plt.title(f'{col} 성별분포')
    plt.xlabel('성별')
    plt.ylabel(col)

    plt.show()

# 위 시각화에서 어떤 인사이트를 확인할 수 있나요?
# 남성이 체중, 허리둘레, 신장에 있어 평균 및 중앙값이 더 높아도 수축기 혈앞에서 큰 차이가 나지 않음
# 이상치가 많이 확인되며 샘플링해 추론통계를 할 필요가 있어보임

"""#### 문제15 : 성별에 따른 흡연상태의 비율을 시각화해보세요"""

health_df['흡연상태'].value_counts()

sex_smoking = health_df.groupby(by='성별')['흡연상태'].value_counts(normalize=True).reset_index(name='비율')

plt.figure(figsize = (5, 5))
sns.barplot(data = sex_smoking, x = '성별', y = '비율', hue='흡연상태')
plt.title('성별에 따른 흡연비율')
plt.xlabel('성별')
plt.ylabel('비율')

plt.show()

# 위 시각화에서 어떤 인사이트를 확인할 수 있나요?
# 여성의 경우 비흡연 비율이 80퍼 이상인 것을 확인할 수 있음.
# 흡연을 이어가는 경우 남성과 여성의 비율은 큰 차이가 발생하고 있지 않음.

"""#### 문제16 : 연령대별로 주요 건강 지표(신장, 체중, 허리둘레, 수축기혈압)를 분석해보세요.
- 연령대별로 이러한 지표들의 평균 값을 계산하여 피봇테이블을 생성하세요.
"""

health_df.head(1)

health_df.pivot_table(index='연령대(5세단위)', values=['신장(5cm단위)', '체중(5kg단위)', '허리둘레', '수축기혈압'], aggfunc='mean')

# 위 데이터에서 어떤 인사이트를 확인할 수 있나요?
# 나이가 많아질수록 수축기 혈압이 상승
# 체중 및 신장은 나이가 많아질수록 감소하는 경향을 보임.

"""#### 문제17 : 각 지표별로 연령대에 따른 평균값의 변화 추이를 그래프로 시각화해보세요."""

select_columns = ['신장(5cm단위)','체중(5kg단위)', '허리둘레', '수축기혈압']
age_pivot = health_df.pivot_table(index='연령대(5세단위)', values=['신장(5cm단위)', '체중(5kg단위)', '허리둘레', '수축기혈압'], aggfunc='mean')

for col in select_columns:
    plt.figure(figsize=(10, 5))
    sns.lineplot(data=age_pivot, x='연령대(5세단위)', y=col, marker='o')
    plt.title(f'{col}의 연령별 평균 변화')
    plt.xlabel('연령대(5세단위)')
    plt.ylabel(f'{col} 평균')
    plt.grid(True)

    plt.show()

"""#### 문제18 : BMI를 계산하고, 각 범주별로 분류해부세요.

체질량 지수(BMI)는 개인의 체중(kg)을 신장(m)의 제곱으로 나눈 값으로 계산하며, 비만도를 판단하는 데 널리 사용됩니다. BMI를 계산하여 각 개인의 비만도를 분류해보세요.


$$BMI= \frac{체중(kg)}{신장(m)^2}$$

BMI에 따른 비만도 분류는 다음과 같습니다:

- 저체중: BMI < 18.5
- 정상 체중: 18.5 ≤ BMI < 25
- 과체중: 25 ≤ BMI < 30
- 비만: BMI ≥ 30

세계보건기구(WHO)의 BMI 분류는 다음과 같습니다:

- 저체중: BMI < 18.5
- 정상: 18.5 ≤ BMI < 24.9
- 과체중: 24.9 ≤ BMI < 30
- 비만: BMI ≥ 30
"""

health_df['bmi'] = health_df['체중(5kg단위)'] / (health_df['신장(5cm단위)']/100) ** 2

def who_bmi(bmi):
    if bmi < 18.5:
        return '저체중'
    elif 18.5 <= bmi < 25:
        return '정상체중'
    elif 25 <= bmi < 30:
        return '과체중'
    else:
        return '비만'

health_df['비만도분류'] = health_df['bmi'].apply(who_bmi)

health_df['비만도분류'].unique()

"""#### 문제19 : BMI 대한 기초 통계량을 확인해보세요."""

# BMI에 관한 기초 통계량 계산
health_df['bmi'].describe()

"""#### 문제20 : BMI에 대한 분포를 더 자세히 살펴보기 위해 히스토그램과 박스 플롯을 사용해 시각화해보세요."""

# 히스토그램
fig, ax = plt.subplots(figsize=(5, 5))
sns.histplot(data=health_df, x='bmi', bins=100)

plt.show()

# 박스플롯
plt.figure(figsize=(5, 5))

sns.boxplot(data=health_df, y='bmi')
plt.show()

# 위 시각화에서 어떤 인사이트를 확인할 수 있나요?
# 대체로 '정상체중','과체중' 사이에 대부분이 분포하며 많은 수를 차지하지만, 데이터의 개수가 많은 많큼 outlier도 많은 것으로 확인

"""#### 문제21 : BMI 범주별 분포를 분석해보세요.
- 위에서 분류한 각 범주별로 인구 분포를 확인해보세요.
"""

person_df = health_df.pivot_table(index='비만도분류', columns='시도코드', values='bmi', aggfunc='count')
person_df = person_df.sort_values(by='비만도분류', ascending=False)
person_df

select_columns = ['신장(5cm단위)','체중(5kg단위)', '허리둘레', '수축기혈압']
age_pivot = health_df.pivot_table(index='연령대(5세단위)', values=['신장(5cm단위)', '체중(5kg단위)', '허리둘레', '수축기혈압'], aggfunc='mean')

for col in select_columns:

    plt.figure(figsize=(10, 5))

    sns.lineplot(data=age_pivot, x='연령대(5세단위)', y=col, marker='o')
    plt.title(f'{col}의 연령별 평균 변화')
    plt.xlabel('연령대(5세단위)')
    plt.ylabel(f'{col} 평균')
    plt.grid(True)

    plt.show()

plt.figure(figsize=(10, 5))

sns.heatmap(data=person_df, annot=True, fmt='d', cmap='YlGnBu')

plt.show()

# 위 시각화에서 어떤 인사이트를 확인할 수 있나요?
#41번 코드 지역에 정상체중과 과체중이 많은것을 확인할 수 있음.

"""#### 문제22 : 비만도(BMI 범주)와 다른 건강 지표(수축기혈압, 이완기혈압, 식전혈당) 간의 관계를 살펴보세요
- 기술 통계와 시각화를 모두 진행해주세요.
"""

new_col = ['수축기혈압', '이완기혈압', '식전혈당(공복혈당)']
health_df.pivot_table(index='비만도분류', values=new_col, aggfunc=['mean', 'min', 'max', 'std'])

for col in new_col:
    plt.figure(figsize=(10, 5))

    sns.boxplot(x='비만도분류', y=col, data=health_df)
    plt.title(f'{col} 별 비만도 분류')
    plt.xlabel('비만도')
    plt.ylabel(col)

    plt.show()

# 위 데이터에서 어떤 인사이트를 확인할 수 있나요?
# bmi 수치가 올라갈수록 수축기 혈압 및 이완기 혈압, 식전혈당 모두 올라가는것으로 확인

"""#### 문제23 : 연령대 및 성별에 따른 BMI 변화를 분석해보세요.
- 연령대가 증가함에 따라 BMI가 어떻게 변화하는지, 그리고 남성과 여성 간의 차이가 있는지를 파악해보세요.
- 데이터를 성별과 연령대 코드로 그룹화하여 각 그룹의 평균 BMI를 계산하고 시각화해보세요.  
"""

# 연령대, 성별 그룹화 및 각 그룹별 bmi 평균값 계산
bmi_last = health_df.groupby(['연령대(5세단위)', '성별'])['bmi'].mean().reset_index()
# 피벗 테이블 생성
bmi_pivot = bmi_last.pivot_table(index='연령대(5세단위)', columns='성별', values='bmi')

bmi_pivot

bmi_df = health_df[['연령대(5세단위)', 'bmi', '성별']]

fig, ax = plt.subplots(figsize=(10, 5))

sns.lineplot(x=bmi_df['연령대(5세단위)'], y=bmi_df['bmi'], hue=bmi_df['성별'], ci=None)
plt.legend(title='성별', labels=['남성', '여성'])

plt.show()

# 젊은 여성 누락으로 원본데이터로 반영
# bmi 칼럼 추가
health_df['bmi'] = health_df['체중(5kg단위)'] / (health_df['신장(5cm단위)']/100) ** 2

def who_bmi(bmi):
    if bmi < 18.5:
        return '저체중'
    elif 18.5 <= bmi < 25:
        return '정상체중'
    elif 25 <= bmi < 30:
        return '과체중'
    else:
        return '비만'

health_df['비만도분류'] = health_df['bmi'].apply(who_bmi)

# 연령대 맵핑 한 칼럼 교체
health_df.rename(columns={'연령대코드(5세단위)':'연령대(5세단위)'}, inplace=True)
health_df['연령대(5세단위)'] = health_df['연령대(5세단위)'].replace(age_group_mapping)

bmi_df = health_df[['연령대(5세단위)', 'bmi', '성별']]

fig, ax = plt.subplots(figsize=(10, 5))

sns.lineplot(x=bmi_df['연령대(5세단위)'], y=bmi_df['bmi'], hue=bmi_df['성별'], ci=None)
plt.legend(title='성별', labels=['남성', '여성'])

plt.show()

# 위 시각화에서 어떤 인사이트를 확인할 수 있나요?
# 남성은 30대 초반에 bmi 수치가 가장 높은 것이 확인되며 이후 점차 감소하는 경향으로 보임.
# 여성은 70대 초반에 bmi 수치가 가장 높은것으로 확인되며, 70개까지 꾸준히 상승하는 경향을 보임
# 남성은 30대 초반 대상으로 여성보다 이른시기에 bmi 수치를 관리하는 것이 좋음. 여성은 지속적으로 bmi 수치를 확인하며 천천히 관리하는 전략이 중요

"""## 마무리

다양한 통계 및 시각화 분석을 진행하였습니다. 모두들 수고하셨습니다.    
제공된 문제 이외에도 다양한 분석을 진행할 수 있습니다. 마음껏 도전해보세요!
"""